---
- hosts: all
  become: true
  remote_user: agonzo
  vars:
    pip_install_packages:
      - name: docker
    
    docker_users:
      - agonzo

  roles:
    - role: geerlingguy.docker
      tags:
        - docker

    - role: geerlingguy.pip
      tags: 
        - geerlingguy.pip
    
    - role: portainer
      tags:
        - portainer
